export const DATABASE_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ID!
export const WORKSPACE_ID = process.env.NEXT_PUBLIC_APPWRITE_WORKSPACE_ID!
export const MEMBER_ID = process.env.NEXT_PUBLIC_APPWRITE_MEMBER_ID!
export const PROJECT_ID = process.env.NEXT_PUBLIC_APPWRITE_PROJECT_ID!
export const TASK_ID = process.env.NEXT_PUBLIC_APPWRITE_TASK_ID!
export const IMAGE_BUCKET_ID = process.env.NEXT_PUBLIC_APPWRITE_IMAGE_BUCKET_ID!
